# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
