# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-26 09:09
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210126_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='customers/', verbose_name='Image'),
        ),
    ]
