# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-22 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ('sale',), 'verbose_name': '_(sale item)', 'verbose_name_plural': '_(sale items)'},
        ),
    ]
