# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-23 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210123_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-date',), 'verbose_name': '_(sale)', 'verbose_name_plural': '_(sale)'},
        ),
    ]
